Cocktail recipe refactoring
kinest1997/Shaker pull request #44
Opened 2022-01-26 15:24 UTC by kinest1997

UIMenu 관련 index를 전달하거나 다른 방법을 못찾아서 뷰컨안에 publishSubject 하나 두고 그것에 onnext로 이벤트를 전달해주는형식으로 바꿈, cellupdate 할때마다 개별의 셀을 업데이트 하는 방식은 그 셀이 잠깐 사라졌다 다시 그려질떄 또 변경되어버려서 셀탭될때도 뷰를 새로 로드하는형식으로 변경함.  reset 버튼을누를때마다 그것을 가상의 indexPath로 변경해서 scan에 합친 다음 가상의 IndexPath 들어올때마다 초기화 시키도록 변경함.

2022-01-27 06:21 UTC, fimuxd commented
일단 코멘트만 봤을 땐
• ViewController 안에 Subject가 있는건 무슨..? ViewModel이 아니라?
• 셀이 탭 될 때마다 relodeData() 한 다는 것임? 절대 🙅 
• scan 처리는 괜찮은 듯

2022-01-27 08:55 UTC, kinest1997 commented
근데 그 셀이 탭 될때 마다 그 셀만 업데이트 하는방식으로할떄 보여지는 셀이 전부일때는 상관없는데 만약에 스크롤해서 내려갔다가 다시돌아와서 셀이 새로 그려질때는 또 그전의 데이터를 받아와서 그릴텐데 그러면 셀이 탭될때마다 테이블뷰가 바라보고 있는 정보를 새로고침해주는게 맞지않을까ㅏ

2022-01-28 02:10 UTC, fimuxd commented
그런 경우에는 `prepareForReuse`를 찾아보세요

2022-01-28 02:14 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +    var nowShowingRecipes = PublishSubject<[Cocktail]>()
view model에서만 쓴다는 의미라면 앞에 private 을 붙여주면 그렇게 되겠지

2022-01-28 02:17 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +            }
```suggestion
            .flatMapLatest(model.getRecipeRx)
```

2022-01-28 02:22 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +            .asObservable()
.asObservable() 없어도 될듯

2022-01-28 02:23 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        let finalResultRecipes = Observable.combineLatest(firstRecipe, filterviewModel.conditionsOfCocktail, textOutput, filterOptionTapped){ recipe, conditions, searchText, sortingStandard -> [Cockt
```suggestion
        let finalResultRecipes = Observable
        .combineLatest(
        firstRecipe, 
        filterviewModel.conditionsOfCocktail, 
        textOutput, 
        filterOptionTapped
        ){ recipe, conditions, searchText, sortingStandard -> [Cocktail] in
```

2022-01-28 02:23 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        let finalResultRecipes = Observable.combineLatest(firstRecipe, filterviewModel.conditionsOfCocktail, textOutput, filterOptionTapped){ recipe, conditions, searchText, sortingStandard -> [Cockt
combineLatest, merge 같은 경우 어떤 아이들을 넣었는지 보기 좋게 나누어줍시다

2022-01-28 02:24 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +                color: conditions[5].condition as! [Cocktail.Color]
[0], [1] 이렇게 해당하는 부분에 값이 없다면 어떻게 되는거죠

2022-01-28 02:25 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        }
여기 인덴트좀 어떻게 해주세요...

2022-01-28 02:26 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        let nowRecipe = Observable.merge(finalResultRecipes, firstRecipe)
merge는 순서를 보장하지 않습니다

2022-01-28 02:29 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CocktailRecipeModel.swift
> +    }
지금은 guard 문 통과 여부를 떠나서 다 .success를 주고 있는데
나중에 error 처리도 세분화 해주면 좋을 듯

2022-01-28 02:31 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CocktailRecipeModel.swift
> +    }
이 함수 좀 더 나누는 것도 좋을 것 같아요

2022-01-28 02:37 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +        tableView.register(CocktailListCell.self, forCellReuseIdentifier: "CocktailListCell")
얘도 그냥 attribute() 함수안에 넣는게

2022-01-28 02:38 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            .startWith(.name)
이 비슷한 코드 viewModel에도 있었던것 같음.
아니면 viewmodel로 옮기는게 좋겠음. 
view의 역할은 그냥 이벤트를 옮기는 것만

2022-01-28 02:39 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            }
이거 rx 코드 있을거야.
.emit(to: filterView.rx.isHidden)
그리고 무조건 true라면 dismissFilterView가 viewModel에서 항상 true를 주는 것으로

2022-01-28 02:43 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            }
이렇게 따로 하지말고 위 코드랑 하나로 합칠 수 있을 듯 
```swift
var isFilterViewHidden: Signal<Bool> { get }
...
// binder 함수
isFilterViewHidden
   .emit(to: filterView.rx.isHidden)
   .disposed(by: disposeBag)
...
//viewModel
self.isFilterViewHidden = Observable
            .merge(
               hideFilterView.map { true }
               showFilterView.map { false }
            )
            .asSignal()
```
이런 식으로

2022-01-28 02:43 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            }
얘도 마찬가지

2022-01-28 02:43 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            .drive(self.tableView.rx.items(cellIdentifier: "CocktailListCell", cellType: CocktailListCell.self)) { int, cocktail, cell in
int 안쓴다면 _ 처리

2022-01-28 02:44 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +        navigationItem.searchController = searchBar
얘는 attribute 성격에 더 가까운듯

2022-01-28 02:44 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            $0.leading.trailing.bottom.equalToSuperview()
= edges.equalToSuperView()

2022-01-28 02:45 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilterViewModel.swift
> +    var showFilterView = PublishSubject<Void>()
viewModel에서 전달하는데 왠 PublishSubject? 심지어 뷰에서 쓰는것도 아님

2022-01-28 02:45 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilterViewModel.swift
> +    var conditionsOfCocktail: Observable<[FilteredView.FilterData]>
이것도 뷰에서 쓰는게 아님. 굳이 bindable에 있을 이유가 없음

2022-01-28 03:13 UTC, fimuxd requested changes
1차 리뷰 완료

2022-01-28 03:13 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +    var conditionsOfCocktail: Observable<[FilteredView.FilterData]> { get }
뷰에 없는데요?

2022-01-28 03:13 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +    var cellData: Observable<[SectionOfFilterCell]> { get }
UI 로직이라면 Drive로

2022-01-28 03:13 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +    var viewWillAppear: PublishSubject<Void> { get }
PublishRelay
다음에 나오는거부터는 코멘트 안달겠음. 다 바꿀것

2022-01-28 03:13 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +        tableView.register(FilterViewCell.self, forCellReuseIdentifier: "filterCell")
attribute에 넣어줄것. 굳이 빼는 이유가?

2022-01-28 03:13 UTC, fimuxd commented on Cocktail/Cocktail/MainView/CocktailRecipe/SearchView/SearchController.swift
> +        self.searchBar.keyboardType = .default
do 로 묶어도 될듯

2022-01-31 11:06 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +    var nowShowingRecipes = PublishSubject<[Cocktail]>()
완료

2022-01-31 11:06 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +    var viewWillAppear = PublishSubject<Void>()
완료

2022-01-31 11:09 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +            }
완료

2022-01-31 11:14 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        let finalResultRecipes = Observable.combineLatest(firstRecipe, filterviewModel.conditionsOfCocktail, textOutput, filterOptionTapped){ recipe, conditions, searchText, sortingStandard -> [Cockt
완료

2022-01-31 11:15 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +                color: conditions[5].condition as! [Cocktail.Color]
무조건 순서대로 되어있기때문에 괜찮습니다

2022-01-31 11:16 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        }
이상하게...완료

2022-01-31 11:17 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CoccktailRecipeViewModel.swift
> +        let nowRecipe = Observable.merge(finalResultRecipes, firstRecipe)
앞부분은 뮤조건 한번만 나타나기때문에 머지로 하였습니다

2022-01-31 11:17 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/CocktailRecipeModel.swift
> +    }
네 알겠습니다

2022-01-31 11:18 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +        tableView.register(CocktailListCell.self, forCellReuseIdentifier: "CocktailListCell")
완료

2022-01-31 11:22 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            .startWith(.name)
완료

2022-01-31 12:03 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            }
완료

2022-01-31 12:26 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            }
완료

2022-01-31 12:27 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +        navigationItem.searchController = searchBar
완료

2022-01-31 12:27 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/CocktailRecipe/RxCocktailRecipeView.swift
> +            $0.leading.trailing.bottom.equalToSuperview()
완료

2022-01-31 12:28 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilterViewModel.swift
> +    var showFilterView = PublishSubject<Void>()
발견하여 삭제...

2022-01-31 12:28 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilterViewModel.swift
> +    var conditionsOfCocktail: Observable<[FilteredView.FilterData]>
완료

2022-01-31 12:28 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilterViewModel.swift
> +    var viewWillAppear = PublishSubject<Void>()
완료

2022-01-31 12:44 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilterViewModel.swift
> +            }
완료

2022-01-31 12:50 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +    var conditionsOfCocktail: Observable<[FilteredView.FilterData]> { get }
정말 고뇌의 잔재들이 사방에..뷰가 아니라 슈퍼뷰모델로 가는것이였음

2022-01-31 12:57 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +    var cellData: Observable<[SectionOfFilterCell]> { get }
옵저버블이라고 생각해서 아무생각없이 했구만... 변경완료

2022-01-31 12:57 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +    var viewWillAppear: PublishSubject<Void> { get }
다 바꾸었습니다!

2022-01-31 12:58 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/FilterView/FilteredView.swift
> +        tableView.register(FilterViewCell.self, forCellReuseIdentifier: "filterCell")
뭔가 애매했다는 기분? 이제 전부 변경하겠음

2022-01-31 12:58 UTC, kinest1997 commented on Cocktail/Cocktail/MainView/CocktailRecipe/SearchView/SearchController.swift
> +        self.searchBar.keyboardType = .default
넵

2022-02-07 05:26 UTC, fimuxd approved these changes

2022-02-07 14:37 UTC, merged